### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by realkarych**
Fixed: app entrypoint; app-crashing if .env variables wasn't created; tpl -> j2 according to [this answer](https://stackoverflow.com/questions/29590931/is-there-an-idiomatic-file-extension-for-jinja-templates).

### CODE REVIEW

**Comment by alexey-goloburdin** [comment]
@yakarych thank you for PR!

About templates extension — Jinja documentation says that `.jinja` extension [is recommended for template files](https://jinja.palletsprojects.com/en/3.0.x/templates/#template-file-extension). Why use `.j2`?

**Comment by realkarych** [comment]
@alexey-goloburdin Ansible uses `.j2` and it's compatible with jinja. `.jinja`, `.jinja2`, `.j2` are actively used, supported by code editors and relevant. There is no difference

**Comment by yakarych** [comment]
> @alexey-goloburdin Ansible uses `.j2` and it's compatible with jinja. `.jinja`, `.jinja2`, `.j2` are actively used, supported by code editors and relevant.

**Comment by alexey-goloburdin** [comment]
> @alexey-goloburdin Ansible uses `.j2` and it's compatible with jinja. `.jinja`, `.jinja2`, `.j2` are actively used, supported by code editors and relevant. There is no difference

Yep, tested in vs code, `.j2` works well with jinja plugin installed, but `.jinja` doesn't work:) So, use `j2`, ok!

**Pull request merged**
